### PR TITLE
Update blade.sublime-syntax

### PR DESCRIPTION
**Pull request by vanekj**
Fixed highlighting problem with Sublime 3 build 3114

### CODE REVIEW

**Comment by rginnow** [comment]
This worked great. Edited the file myself locally. Thanks!

**Comment by wlcx** [comment]
Manually installed your patch until this gets merged. Thanks!

**Comment by overcrookd** [comment]
Seems to have fixed it, thanks! Although there's a bug when having an css inside a style tag with @keyframes (removing the keyframes portion fixes it) :

`    <style>
        #page-loader{position:fixed;left:0;top:0;width:100%;height:100%;text-align:center;background-color:#FFF;z-index:999}.loader{margin:60px auto;font-size:6px;position:relative;text-indent:-9999em;border-top:.8em solid rgba(218,47,39,.2);border-right:.8em solid rgba(218,47,39,.2);border-bottom:.8em solid rgba(218,47,39,.2);border-left:.8em solid #da2f27;-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);-webkit-animation:load8 1.1s infinite linear;animation:load8 1.1s infinite linear}.loader,.loader:after{border-radius:50%;width:6em;height:6em}@-webkit-keyframes load8{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes load8{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}
    </style>`

**Comment by bradgenereux** [comment]
Thank you so much. This worked perfectly!

**Comment by sebbuku** [comment]
Thanks fixed it for me.

**Comment by santiagazo** [comment]
Sorry to ask this but...can anyone tell me how to find this file on my local machine to fix it?

**Comment by sebbuku** [comment]
I used the PackageResourceViewer ( https://packagecontrol.io/packages/PackageResourceViewer ) to extract the package and then edited the sublime-syntax file.

**Comment by santiagazo** [comment]
@sebbuku OMG dude you freaking rock. Thank you soooo much. *beating my head against the wall for 2 hours!

**Comment by Skintillion** [comment]
Odd, this didn't fix it for me.

image

**Comment by dattz** [comment]
Working great! Thank you so much!

**Comment by diegoahg** [comment]
If you did the fix and the problem persist, you have to change the line 61 with '(?!.*\))' also.

**Comment by Skintillion** [comment]
Thanks diehoahg, it should be '(?!.*\))' though, otherwise i get a regex error.

**Comment by CLOUGH** [comment]
The autocomplete is still not working for build 3114. Reverted back to PHP to get this feature.

**Pull request merged**
