### PR TITLE
This will fix the PHP commenting issue

### PR DESCRIPTION
**Pull request by djekl**

### CODE REVIEW

**Comment by jdavidbakr** [comment]
I don't think this fixed the issue, in blade I'm getting the HTML comment styles instead of the Blade comment styles
screen shot 2016-06-10 at 9 43 43 am

**Comment by djekl** [comment]
Yeah, I now have the same. I had it working... thats why I made the PR 😢

**Comment by zaynali53** [comment]
@djekl @jdavidbakr Comment toggle issue has been resolved. I've just pushed a new release 1.5.8.8. You can try it now. 

Here is the screenshot of my blade test.

fix

**Comment by jdavidbakr** [comment]
So far so good!  Thanks again!

**Comment by jdavidbakr** [comment]
I have run into something else that is now broken - previously I was able to tab and create HTML elements, i.e.:

```
.test [tab]
```
would expand to
```
<div class="test"></div>
```

but this is not working now.  I feel like this might be another package that handled that, but it was working with the previous version of laravel-blade and is no longer working.

**Comment by zaynali53** [comment]
@jdavidbakr This issue has been resolved. You can upgrade the package `v1.5.8.9` :)

**Comment by jdavidbakr** [comment]
@zaynali53 - thank you for all the effort you're putting into getting this package working - I feel like we're in a bit of a circular vortex though, the comments in my blade file have reverted back to html style.

**Comment by jdavidbakr** [comment]
Here is what I'm getting with the same content of your test you have above

```
<!-- <div></div> -->
{{-- {{ trans('page.content') }} --}}
<!-- @include('master') -->
<!-- @{{ some code }} -->
<!-- <?php echo @name ?> -->
<!-- <?= $name ?> -->
<!-- {!! $name !!} -->
<!-- {{{ $name }}} -->
<!--
<ul>
	<li></li>
	<li></li>
</ul>
 -->
```

**Comment by zaynali53** [comment]
@jdavidbakr i've updated the scopes as some of them were conflicting with each other and now html scope will use html comment and blade scope will use blade comment as it should be so if your cursor is in the html scope then it'll generate it's corresponding comment.

**Because**: Sublime comment settings uses scope to detect where to use what comment.

For example
`@include('master')|` will generate html comment `(html scope)`
`@include('maste|r')` will generate blade comment `(blade scope)`

**Comment by jdavidbakr** [comment]
@zaynali53 I see, although I prefer the previous behavior as I would prefer to keep my comments in my blade file from being delivered in to the client in the HTML.

**Comment by zaynali53** [comment]
@jdavidbakr I agree. This feature was added due to this request https://github.com/Medalink/laravel-blade/issues/125#issuecomment-225416940

**Comment by jdavidbakr** [comment]
@zaynali53 any way it could be an option to turn on or off in the preferences?  If you're on my side as the developer I think the default action should be how it was previously and the change from request #125 could be enabled via an option.

**Comment by zaynali53** [comment]
@jdavidbakr I've just revert back to the blade comment. So now that would be the default comment.

**Pull request closed without merging**
