### PR TITLE
Add shortcode from Blade Wordpress Plugin

### PR DESCRIPTION
**Pull request by heavybeard**
The [Blade Wordpress Plugin](https://it.wordpress.org/plugins/blade/) use specific snippet to blade:
* `wpquery`
* `wpposts`
* `acfrepeater`
* `wpempty`
* `wpend`
* `acfend`

The Loop
```blade
@wpposts
    <a href="{{the_permalink()}}">{{the_title()}}</a><br>
@wpempty
    <p>404</p>
@wpend
```
Turns into...
```html
<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <a href="<?php the_permalink() ?>"><?php the_title() ?></a><br>
<?php endwhile; else: ?>
    <p>404</p>
<?php endif; ?>
```

WP Query
```blade
<ul>
@wpquery(array('post_type' => 'post'))
    <li><a href="{{the_permalink()}}">{{the_title()}}</a></li>
@wpempty
    <li>{{ __('Sorry, no posts matched your criteria.') }}</li>
@wpend
</ul>
```
Turns into....
```html
<ul>
<?php $query = new WP_Query( array('post_type' => 'post') ); ?>
<?php if ( $query->have_posts() ) : ?>
    <?php while ( $query->have_posts() ) : $query->the_post(); ?>
        <li><a href="<?php the_permalink() ?>"> <?php the_title() ?> </a></li>
    <?php endwhile; ?>
<?php else : ?>
    <li><?php _e('Sorry, no posts matched your criteria.') ?></li>
<?php endif; wp_reset_postdata(); ?>
</ul>
```

Advanced Custom Fields
```blade
<ul>
    @acfrepeater('images')
        <li>{{ get_sub_field( 'image' ) }}</li>
    @acfend
</ul>
```
Turns into...
```html
<ul>
    <?php if( get_field( 'images' ) ): ?>
        <?php while( has_sub_field( 'images' ) ): ?>
            <li><img src="<?php the_sub_field( 'image' ) ?>" /></li>
        <?php endwhile; ?>
    <?php endif; ?>
</ul>
```

Check this for all infos: https://it.wordpress.org/plugins/blade/

### CODE REVIEW

**Comment by zaynali53** [comment]
Thanks @heavybeard

**Comment by jbrooksuk** [comment]
I don't believe that this should be included as it's a plugin to Blade, it's not the Blade language.

**Comment by heavybeard** [comment]
Hi @jbrooksuk,
I added it because I found on [blade.sublime-text](https://github.com/Medalink/laravel-blade/blob/master/blade.sublime-syntax#L81) other plugin snippet like `hipchat` and `slack`.

**Comment by jbrooksuk** [comment]
@heavybeard and I'd say the same to them, they're not part of the core language.

**Comment by heavybeard** [comment]
In part I agree with you, but Sublime Text must to help devs to write code faster and easy to read.
The snippets above were created with this purpose and when I use them I prefer to see them like the core's blade snippets.

There's three ways, in my opinion:
* create a blade snippet highlighter plugin (maybe to integrate with [Blade Snippets](https://github.com/dev4dev/blade-snippets))
* create a regex for every string like `@snippet` and not with defined snippet
* remove all third-part's snippets (I hate this option)

**Comment by heavybeard** [comment]
The snippets were added on Blade Snippets plugin too with this PR https://github.com/dev4dev/blade-snippets/pull/34

**Comment by Medalink** [comment]
I am fine with these being in the highlighter as custom compilers. They are colored different than built in Laravel compilers so Laravel devs should not have any issues.

**Pull request merged**
